
spring:
  application:
    name: clinic_core-dev

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: clinic_core

  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/clinicdb
    username: clinic_db
    password: root
